# Use Node.js image
FROM node:22.13.1-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the application
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]

