version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - ./backend/.env.development.testing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development # Specify the custom Dockerfile name
    container_name: nestjs_container
    volumes:
      - ./backend:/app # Mount the local directory into the container
      - /app/node_modules # Prevent conflicts between local and container node_modules
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.development.testing
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: nextjs_container
    volumes:
      - ./frontend:/app # Mount the local directory into the container
      - /app/node_modules # Prevent conflicts between local and container node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
